.TH cxhkd 1 cxhkd\-VERSION
.SH NAME
cxhkd \- Per context X hotkey daemon
.SH SYNOPSIS
cxhkd
.OP -v
.SH DESCRIPTION
Run commands defined as strings in the python module ~/.confi/cxhkd/cxhkd.py
.SH OPTIONS
.TP
.B \-v
print the version
.SH IMPLEMENTATION
One of two sets of keys is, at any given moment, grabbed by this daemon.
The first set contains code/mask pairs in the config module's variable names, the second the entire keyboard.
The daemon alternates from one set to another based on the current context.

The context is the set of code/mask pairs being currently listened to by the daemon.
The context can have nested contexts, identified by code/mask pairs, forming a tree structure.
The daemon executes a command bound to the pressed code/mask or initiates/maintains a streak if the pressed code/mask pair identifies a nested context.
During a streak, the daemon grabs the keyboard until any key not listed in the current context or a command stops it.

